tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: true
endOfLine: crlf
embeddedLanguageFormatting: auto
